### ISSUE TITLE
Enemies cannot pathfind to diagonal tiles as they're unwalkable

### ISSUE THREAD

**Issue by jamiefp17** [arcturus125/Agile-Assessment#42]
![image](https://user-images.githubusercontent.com/57445543/114743468-9f3f6100-9d44-11eb-85a2-8e2db9675272.png)

**Comment by arcturus125** [comment]
**Two proposed fixes:**

**idea 1:**
change the walkable map to allow enemies to walk over that tile , but NOT allow the player to place towers there
(you will need to add a new colour to the map that is specific to enemies and ignored by towers)

**idea 2**
make the pathfinding find the tile NEXT TO the player instead of the tile the player is on.
this is a "cowboy fix" and i do not recommend it. but if all else fails, this can be a backup
